//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapucplanetWA.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", ConfigurationName="Servicio.PeliculaWS")]
    public interface PeliculaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/modificarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PapucplanetWA.Servicio.modificarResponse modificar(PapucplanetWA.Servicio.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/modificarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/modificarResponse")]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.modificarResponse> modificarAsync(PapucplanetWA.Servicio.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/eliminarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PapucplanetWA.Servicio.eliminarResponse eliminar(PapucplanetWA.Servicio.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/eliminarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/eliminarResponse")]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.eliminarResponse> eliminarAsync(PapucplanetWA.Servicio.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/insertarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PapucplanetWA.Servicio.insertarResponse insertar(PapucplanetWA.Servicio.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/insertarRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/insertarResponse")]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.insertarResponse> insertarAsync(PapucplanetWA.Servicio.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/obtenerPorIdRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PapucplanetWA.Servicio.obtenerPorIdResponse obtenerPorId(PapucplanetWA.Servicio.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/obtenerPorIdRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.obtenerPorIdResponse> obtenerPorIdAsync(PapucplanetWA.Servicio.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/listarTodosRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PapucplanetWA.Servicio.listarTodosResponse listarTodos(PapucplanetWA.Servicio.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.papucplanet.pucp.edu.pe/PeliculaWS/listarTodosRequest", ReplyAction="http://services.papucplanet.pucp.edu.pe/PeliculaWS/listarTodosResponse")]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.listarTodosResponse> listarTodosAsync(PapucplanetWA.Servicio.listarTodosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.papucplanet.pucp.edu.pe")]
    public partial class pelicula : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private double duracionField;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private int idPeliculaField;
        
        private string sinopsisField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPelicula {
            get {
                return this.idPeliculaField;
            }
            set {
                this.idPeliculaField = value;
                this.RaisePropertyChanged("idPelicula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                this.sinopsisField = value;
                this.RaisePropertyChanged("sinopsis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.papucplanet.pucp.edu.pe")]
    public enum genero {
        
        /// <remarks/>
        ACCION,
        
        /// <remarks/>
        COMEDIA,
        
        /// <remarks/>
        DRAMA,
        
        /// <remarks/>
        DOCUMENTAL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PapucplanetWA.Servicio.pelicula pelicula;
        
        public modificarRequest() {
        }
        
        public modificarRequest(PapucplanetWA.Servicio.pelicula pelicula) {
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPelicula;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int idPelicula) {
            this.idPelicula = idPelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PapucplanetWA.Servicio.pelicula pelicula;
        
        public insertarRequest() {
        }
        
        public insertarRequest(PapucplanetWA.Servicio.pelicula pelicula) {
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPelicula;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int idPelicula) {
            this.idPelicula = idPelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PapucplanetWA.Servicio.pelicula @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(PapucplanetWA.Servicio.pelicula @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://services.papucplanet.pucp.edu.pe", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.papucplanet.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PapucplanetWA.Servicio.pelicula[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(PapucplanetWA.Servicio.pelicula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeliculaWSChannel : PapucplanetWA.Servicio.PeliculaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeliculaWSClient : System.ServiceModel.ClientBase<PapucplanetWA.Servicio.PeliculaWS>, PapucplanetWA.Servicio.PeliculaWS {
        
        public PeliculaWSClient() {
        }
        
        public PeliculaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeliculaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PapucplanetWA.Servicio.modificarResponse PapucplanetWA.Servicio.PeliculaWS.modificar(PapucplanetWA.Servicio.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(PapucplanetWA.Servicio.pelicula pelicula) {
            PapucplanetWA.Servicio.modificarRequest inValue = new PapucplanetWA.Servicio.modificarRequest();
            inValue.pelicula = pelicula;
            PapucplanetWA.Servicio.modificarResponse retVal = ((PapucplanetWA.Servicio.PeliculaWS)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.modificarResponse> PapucplanetWA.Servicio.PeliculaWS.modificarAsync(PapucplanetWA.Servicio.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PapucplanetWA.Servicio.modificarResponse> modificarAsync(PapucplanetWA.Servicio.pelicula pelicula) {
            PapucplanetWA.Servicio.modificarRequest inValue = new PapucplanetWA.Servicio.modificarRequest();
            inValue.pelicula = pelicula;
            return ((PapucplanetWA.Servicio.PeliculaWS)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PapucplanetWA.Servicio.eliminarResponse PapucplanetWA.Servicio.PeliculaWS.eliminar(PapucplanetWA.Servicio.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int idPelicula) {
            PapucplanetWA.Servicio.eliminarRequest inValue = new PapucplanetWA.Servicio.eliminarRequest();
            inValue.idPelicula = idPelicula;
            PapucplanetWA.Servicio.eliminarResponse retVal = ((PapucplanetWA.Servicio.PeliculaWS)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.eliminarResponse> PapucplanetWA.Servicio.PeliculaWS.eliminarAsync(PapucplanetWA.Servicio.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PapucplanetWA.Servicio.eliminarResponse> eliminarAsync(int idPelicula) {
            PapucplanetWA.Servicio.eliminarRequest inValue = new PapucplanetWA.Servicio.eliminarRequest();
            inValue.idPelicula = idPelicula;
            return ((PapucplanetWA.Servicio.PeliculaWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PapucplanetWA.Servicio.insertarResponse PapucplanetWA.Servicio.PeliculaWS.insertar(PapucplanetWA.Servicio.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(PapucplanetWA.Servicio.pelicula pelicula) {
            PapucplanetWA.Servicio.insertarRequest inValue = new PapucplanetWA.Servicio.insertarRequest();
            inValue.pelicula = pelicula;
            PapucplanetWA.Servicio.insertarResponse retVal = ((PapucplanetWA.Servicio.PeliculaWS)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.insertarResponse> PapucplanetWA.Servicio.PeliculaWS.insertarAsync(PapucplanetWA.Servicio.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<PapucplanetWA.Servicio.insertarResponse> insertarAsync(PapucplanetWA.Servicio.pelicula pelicula) {
            PapucplanetWA.Servicio.insertarRequest inValue = new PapucplanetWA.Servicio.insertarRequest();
            inValue.pelicula = pelicula;
            return ((PapucplanetWA.Servicio.PeliculaWS)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PapucplanetWA.Servicio.obtenerPorIdResponse PapucplanetWA.Servicio.PeliculaWS.obtenerPorId(PapucplanetWA.Servicio.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public PapucplanetWA.Servicio.pelicula obtenerPorId(int idPelicula) {
            PapucplanetWA.Servicio.obtenerPorIdRequest inValue = new PapucplanetWA.Servicio.obtenerPorIdRequest();
            inValue.idPelicula = idPelicula;
            PapucplanetWA.Servicio.obtenerPorIdResponse retVal = ((PapucplanetWA.Servicio.PeliculaWS)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.obtenerPorIdResponse> PapucplanetWA.Servicio.PeliculaWS.obtenerPorIdAsync(PapucplanetWA.Servicio.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PapucplanetWA.Servicio.obtenerPorIdResponse> obtenerPorIdAsync(int idPelicula) {
            PapucplanetWA.Servicio.obtenerPorIdRequest inValue = new PapucplanetWA.Servicio.obtenerPorIdRequest();
            inValue.idPelicula = idPelicula;
            return ((PapucplanetWA.Servicio.PeliculaWS)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PapucplanetWA.Servicio.listarTodosResponse PapucplanetWA.Servicio.PeliculaWS.listarTodos(PapucplanetWA.Servicio.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public PapucplanetWA.Servicio.pelicula[] listarTodos() {
            PapucplanetWA.Servicio.listarTodosRequest inValue = new PapucplanetWA.Servicio.listarTodosRequest();
            PapucplanetWA.Servicio.listarTodosResponse retVal = ((PapucplanetWA.Servicio.PeliculaWS)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PapucplanetWA.Servicio.listarTodosResponse> PapucplanetWA.Servicio.PeliculaWS.listarTodosAsync(PapucplanetWA.Servicio.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PapucplanetWA.Servicio.listarTodosResponse> listarTodosAsync() {
            PapucplanetWA.Servicio.listarTodosRequest inValue = new PapucplanetWA.Servicio.listarTodosRequest();
            return ((PapucplanetWA.Servicio.PeliculaWS)(this)).listarTodosAsync(inValue);
        }
    }
}
